remote_theme: daviddarnes/alembic@main

# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache

# Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Lilyël" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/icon.png" # Site logo, also used in jekyll-seo-tag

# Site navigation
navigation_header:
- title: Home
  url: /Home/
- title: Professional Projects
  url: /pro/
- title: Personal Projects
  url: /perso/
- title: School Projects
  url: /school/
- title: Résumé
  url: /resume/
- title: Contact
  url: /contact/
  
navigation_footer:
- title: Lilyel
  url: https://lilyel.github.io/Website/
